package com.beespoon.apollo.ksp

import java.security.MessageDigest

internal object RegistrarEmitter {
    const val PACKAGE = "com.beespoon.apollo.generated"
    const val SERVICE_FILE = "META-INF/services/com.beespoon.apollo.ApolloRegistrar"
    fun className(model: RegistrarModel): String {
        val segment = model.namespace?.replace(Regex("[^A-Za-z0-9]"), "_")?.let { "${it}_" }.orEmpty()
        return "ApolloRegistrar_$segment${hash(model)}"
    }

    fun emit(model: RegistrarModel, className: String): String = buildString {
        appendLine("// Generated by Apollo's KSP processor — do not edit.")
        appendLine("package $PACKAGE")
        appendLine()
        appendLine("public class $className : com.beespoon.apollo.ApolloRegistrar {")
        appendLine("    override fun register(builder: com.beespoon.apollo.ApolloBuilder) {")
        for (config in model.configs) append(emitConfig(config, model.namespace))
        for (base in model.polymorphicBases) appendLine("        builder.polymorphic($base::class)")
        for ((base, subtypes) in model.polymorphicSubtypes) {
            appendLine("        builder.polymorphicSubtypes(")
            appendLine("            $base::class,")
            for (subtype in subtypes) appendLine("            $subtype::class,")
            appendLine("        )")
        }
        appendLine("    }")
        appendLine("}")
    }

    private fun emitConfig(config: RegistrarModel.Config, namespace: String?): String = buildString {
        append(
            "        builder.register(${config.className}::class, name = ${quote(config.name)}, format = ${
                quote(
                    config.format
                )
            }"
        )
        if (namespace != null) append(", namespace = ${quote(namespace)}")
        if (config.directories.isEmpty()) {
            appendLine(")"); return@buildString
        }
        appendLine(") {")
        for (dir in config.directories) {
            appendLine(
                "            directory(${config.className}::`${dir.propertyName}`, name = ${quote(dir.name)})"
            )
        }
        appendLine("        }")
    }

    private fun quote(value: String): String =
        "\"" + value.replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\${'$'}") + "\""

    private fun hash(model: RegistrarModel): String {
        val signature =
            (model.configs.map { it.className } + model.polymorphicBases + model.polymorphicSubtypes.flatMap { (base, subtypes) -> subtypes.map { "$base<-$it" } }).sorted()
                .joinToString("|", prefix = "${model.namespace}|")
        return MessageDigest.getInstance("SHA-1").digest(signature.toByteArray()).joinToString("") { "%02x".format(it) }
            .take(8)
    }
}
